<a href="https://colab.research.google.com/github/asiya00/Data-Science/blob/main/Pandas_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pandas is used for data manipulation, analysis and cleaning

* DataFrame is a 2-Dimensional, size-mutable, potentially hetrogenous tabular data
* Series is 1-Dimensional labelled array capable of holding data of any type

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.Series([1,2,3,4,5],index=[1,2,3,4,5])

1    1
2    2
3    3
4    4
5    5
dtype: int64

In [ ]:
Heights=[1.2,'3.5','4.5',6.5]

In [ ]:
pd.Series(Heights)

0    1.2
1    3.5
2    4.5
3    6.5
dtype: object

In [ ]:
Heights=[1,3.5,4,6]

In [ ]:
pd.Series(Heights)

0    1.0
1    3.5
2    4.0
3    6.0
dtype: float64

In [ ]:
Heights=[1,'3.5',4,6]

In [ ]:
b=np.array(Heights)

In [ ]:
b

array(['1', '3.5', '4', '6'], dtype='<U21')

* U = Unicode
* 21 = Size

In [ ]:
b.dtype

dtype('<U21')

In [ ]:
b= pd.Series(Heights)

In [ ]:
b.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
np.linspace(2,3,num=4, endpoint= True,retstep=True)

(array([2.        , 2.33333333, 2.66666667, 3.        ]), 0.3333333333333333)

In [ ]:
b=pd.Series([1,3.5,4,6])

* Method is a function bound to an object
* Attribute is a variable bound to an object

In [ ]:
c = pd.Series(Heights).size

In [ ]:
c

4

In [ ]:
a=b

In [ ]:
a

0    1.0
1    3.5
2    4.0
3    6.0
dtype: float64

In [ ]:
a.equals(b)

True

In [ ]:
 
#default None
a.name == None

True

In [ ]:
a.name='Numbers'

In [ ]:
a

0    1.0
1    3.5
2    4.0
3    6.0
Name: Numbers, dtype: float64

In [ ]:
a.index.name="Sr.no"
a

Sr.no
0    1.0
1    3.5
2    4.0
3    6.0
Name: Numbers, dtype: float64

In [ ]:
d = pd.date_range("20210225", periods=2)

In [ ]:
d

DatetimeIndex(['2021-02-25', '2021-02-26'], dtype='datetime64[ns]', freq='D')

In [ ]:
df = pd.DataFrame(np.random.randn(2,4), index=d,columns=['A','B','C','D'])
df

A         B         C         D
2021-02-25  0.316477 -0.144339 -0.173174 -0.461841
2021-02-26 -0.184344  0.480628  1.679986  1.565173

In [ ]:
df = pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]], index = d, columns = np.arange(0,5) )
df

0  1  2  3   4
2021-02-25  1  2  3  4   5
2021-02-26  6  7  8  9  10

In [ ]:
df = pd.DataFrame({'A' : [1,2,3,4,5],
                   'B' : pd.date_range('20200225' , periods=5),
                   'C' : pd.Series(1, index=(np.arange(5))),
                   'D' : pd.Series(5, index=(np.arange(5))),
                   'E' : pd.Categorical(["Train","Train","Test","Train","Test"]),
                   'F' : 'Workshop'})

In [ ]:
df

A          B  C  D      E         F
0  1 2020-02-25  1  5  Train  Workshop
1  2 2020-02-26  1  5  Train  Workshop
2  3 2020-02-27  1  5   Test  Workshop
3  4 2020-02-28  1  5  Train  Workshop
4  5 2020-02-29  1  5   Test  Workshop

In [ ]:
df.dtypes

A             int64
B    datetime64[ns]
C             int64
D             int64
E          category
F            object
dtype: object

* How to View Data?

In [ ]:
df.to_numpy()

array([[1, Timestamp('2020-02-25 00:00:00'), 1, 5, 'Train', 'Workshop'],
       [2, Timestamp('2020-02-26 00:00:00'), 1, 5, 'Train', 'Workshop'],
       [3, Timestamp('2020-02-27 00:00:00'), 1, 5, 'Test', 'Workshop'],
       [4, Timestamp('2020-02-28 00:00:00'), 1, 5, 'Train', 'Workshop'],
       [5, Timestamp('2020-02-29 00:00:00'), 1, 5, 'Test', 'Workshop']],
      dtype=object)

In [ ]:
df.describe()

A    C    D
count  5.000000  5.0  5.0
mean   3.000000  1.0  5.0
std    1.581139  0.0  0.0
min    1.000000  1.0  5.0
25%    2.000000  1.0  5.0
50%    3.000000  1.0  5.0
75%    4.000000  1.0  5.0
max    5.000000  1.0  5.0

In [ ]:
d1 = pd.date_range("20210225", periods=10)

In [ ]:
df1 = pd.DataFrame(np.random.randn(10,4), index=d1,columns=['A','B','C','D'])
df1

A         B         C         D
2021-02-25 -0.223142  0.172563  1.328213 -0.396174
2021-02-26 -0.258195 -0.898269  1.534004  2.230910
2021-02-27 -0.144576  0.857741  0.631783  2.730759
2021-02-28 -0.563964  0.682976  0.134919 -0.036175
2021-03-01 -0.516415 -0.140086 -0.331659  0.845632
2021-03-02  0.549316 -1.778492 -1.199401 -0.960869
2021-03-03  0.824688 -0.125578  0.239478  0.292834
2021-03-04 -0.378691  0.055439 -0.448168  1.080126
2021-03-05 -0.238644  0.224865  0.211980  0.323348
2021-03-06  0.531980  0.706118 -0.411751 -1.019778

In [ ]:
df1.describe()

A          B          C          D
count  10.000000  10.000000  10.000000  10.000000
mean   -0.041764  -0.024272   0.168940   0.509061
std     0.491017   0.801639   0.834699   1.248827
min    -0.563964  -1.778492  -1.199401  -1.019778
25%    -0.348567  -0.136459  -0.391728  -0.306174
50%    -0.230893   0.114001   0.173450   0.308091
75%     0.362841   0.568448   0.533707   1.021502
max     0.824688   0.857741   1.534004   2.730759

In [ ]:
df1.sort_index(axis=1, ascending=False)

D         C         B         A
2021-02-25 -0.396174  1.328213  0.172563 -0.223142
2021-02-26  2.230910  1.534004 -0.898269 -0.258195
2021-02-27  2.730759  0.631783  0.857741 -0.144576
2021-02-28 -0.036175  0.134919  0.682976 -0.563964
2021-03-01  0.845632 -0.331659 -0.140086 -0.516415
2021-03-02 -0.960869 -1.199401 -1.778492  0.549316
2021-03-03  0.292834  0.239478 -0.125578  0.824688
2021-03-04  1.080126 -0.448168  0.055439 -0.378691
2021-03-05  0.323348  0.211980  0.224865 -0.238644
2021-03-06 -1.019778 -0.411751  0.706118  0.531980

In [ ]:
df1.sort_values(by='A', ascending=False)

A         B         C         D
2021-03-03  0.824688 -0.125578  0.239478  0.292834
2021-03-02  0.549316 -1.778492 -1.199401 -0.960869
2021-03-06  0.531980  0.706118 -0.411751 -1.019778
2021-02-27 -0.144576  0.857741  0.631783  2.730759
2021-02-25 -0.223142  0.172563  1.328213 -0.396174
2021-03-05 -0.238644  0.224865  0.211980  0.323348
2021-02-26 -0.258195 -0.898269  1.534004  2.230910
2021-03-04 -0.378691  0.055439 -0.448168  1.080126
2021-03-01 -0.516415 -0.140086 -0.331659  0.845632
2021-02-28 -0.563964  0.682976  0.134919 -0.036175

In [ ]:
# Slicing starting from 0th row to 3rd row
df1[0:3]

A         B         C         D
2021-02-25 -0.223142  0.172563  1.328213 -0.396174
2021-02-26 -0.258195 -0.898269  1.534004  2.230910
2021-02-27 -0.144576  0.857741  0.631783  2.730759

In [ ]:
# Slicing using iloc rows along with columns
df1.iloc[0:3,2:4]

C         D
2021-02-25  1.328213 -0.396174
2021-02-26  1.534004  2.230910
2021-02-27  0.631783  2.730759

In [ ]:
# from 0th row to 2nd row of particular selected columns 
df.loc[0:2, ('A','B')] 

A          B
0  1 2020-02-25
1  2 2020-02-26
2  3 2020-02-27

In [ ]:
df.drop('D', axis=1)

A          B  C      E         F
0  1 2020-02-25  1  Train  Workshop
1  2 2020-02-26  1  Train  Workshop
2  3 2020-02-27  1   Test  Workshop
3  4 2020-02-28  1  Train  Workshop
4  5 2020-02-29  1   Test  Workshop

In [ ]:
df

A          B  C  D      E         F
0  1 2020-02-25  1  5  Train  Workshop
1  2 2020-02-26  1  5  Train  Workshop
2  3 2020-02-27  1  5   Test  Workshop
3  4 2020-02-28  1  5  Train  Workshop
4  5 2020-02-29  1  5   Test  Workshop

In [ ]:
df.drop(4,axis=0)

A          B  C  D      E         F
0  1 2020-02-25  1  5  Train  Workshop
1  2 2020-02-26  1  5  Train  Workshop
2  3 2020-02-27  1  5   Test  Workshop
3  4 2020-02-28  1  5  Train  Workshop

* Function Application and Mapping

In [ ]:
def half(s):
  return s*0.5

df[['D','A']].apply(half)

D    A
0  2.5  0.5
1  2.5  1.0
2  2.5  1.5
3  2.5  2.0
4  2.5  2.5

In [ ]:
df[['D','A']].apply(lambda x:x*0.5 , axis = 1)

D    A
0  2.5  0.5
1  2.5  1.0
2  2.5  1.5
3  2.5  2.0
4  2.5  2.5

In [ ]:
df[['E']].applymap(str.upper)

E
0  TRAIN
1  TRAIN
2   TEST
3  TRAIN
4   TEST

In [ ]:
df['F'].map(str.upper)

0    WORKSHOP
1    WORKSHOP
2    WORKSHOP
3    WORKSHOP
4    WORKSHOP
Name: F, dtype: object

In [ ]:
#df.value_counts('E') OR
df['E'].value_counts()

Train    3
Test     2
Name: E, dtype: int64

* Index and Reindexing

In [ ]:
#Index 
pd.Index([1,2,3,4,5,6,7,8,9,0]).values

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [ ]:
df2 = pd.DataFrame(np.random.randn(10,4), index= pd.Index(['A','B','C','D','E','F','G','H','I','J'], name='Alphabets'), columns=pd.Index(['I','II','III','IV'], name='Roman values'))
df2

Roman values         I        II       III        IV
Alphabets                                           
A            -1.042351  0.396239 -0.363974 -0.185126
B             0.859724 -0.392639  0.853598  0.786161
C            -0.674700  0.182811 -1.186566  0.559129
D             0.129249 -0.424662  0.015757 -0.271605
E            -0.578163  1.283488 -1.175926  0.836512
F             0.969954 -0.939907  0.975316  0.789802
G             1.005044 -0.298769 -0.881498 -1.400847
H            -1.067536 -0.278950 -0.533865  1.432076
I             0.375985 -0.699654  1.432534  0.403151
J            -0.504922 -0.569931 -0.404107  0.640058

In [ ]:
df2.reindex(['B','A','C','E','D','G','F','H','J','I'])

Roman values         I        II       III        IV
Alphabets                                           
B             0.859724 -0.392639  0.853598  0.786161
A            -1.042351  0.396239 -0.363974 -0.185126
C            -0.674700  0.182811 -1.186566  0.559129
E            -0.578163  1.283488 -1.175926  0.836512
D             0.129249 -0.424662  0.015757 -0.271605
G             1.005044 -0.298769 -0.881498 -1.400847
F             0.969954 -0.939907  0.975316  0.789802
H            -1.067536 -0.278950 -0.533865  1.432076
J            -0.504922 -0.569931 -0.404107  0.640058
I             0.375985 -0.699654  1.432534  0.403151

In [ ]:
a = df2.index
a

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='object', name='Alphabets')

In [ ]:
# getting locations of Index values in range
a.slice_locs('A','G')

(0, 7)

* Renaming

In [ ]:
df2.rename(columns={"I":1,"II":2,"III":3,"IV":4})

Roman values         1         2         3         4
Alphabets                                           
A            -1.042351  0.396239 -0.363974 -0.185126
B             0.859724 -0.392639  0.853598  0.786161
C            -0.674700  0.182811 -1.186566  0.559129
D             0.129249 -0.424662  0.015757 -0.271605
E            -0.578163  1.283488 -1.175926  0.836512
F             0.969954 -0.939907  0.975316  0.789802
G             1.005044 -0.298769 -0.881498 -1.400847
H            -1.067536 -0.278950 -0.533865  1.432076
I             0.375985 -0.699654  1.432534  0.403151
J            -0.504922 -0.569931 -0.404107  0.640058

* DataFrame Filtering

In [ ]:
df2.filter(items=['I','IV'])

Roman values         I        IV
Alphabets                       
A            -1.042351 -0.185126
B             0.859724  0.786161
C            -0.674700  0.559129
D             0.129249 -0.271605
E            -0.578163  0.836512
F             0.969954  0.789802
G             1.005044 -1.400847
H            -1.067536  1.432076
I             0.375985  0.403151
J            -0.504922  0.640058

In [ ]:
df1.filter(like='-02-',axis=0)

A         B         C         D
2021-02-25 -0.223142  0.172563  1.328213 -0.396174
2021-02-26 -0.258195 -0.898269  1.534004  2.230910
2021-02-27 -0.144576  0.857741  0.631783  2.730759
2021-02-28 -0.563964  0.682976  0.134919 -0.036175

* Arithmetic and Data Alignment

In [ ]:
A = pd.Series([2, 4, 6])
B = pd.Series([1, 3, 5])
A+B

0     3
1     7
2    11
dtype: int64

In [ ]:
A.add(B)

0     3
1     7
2    11
dtype: int64

In [ ]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
C =(A+B)
C.name = "Addition"
C

0    NaN
1    5.0
2    9.0
3    NaN
Name: Addition, dtype: float64

In [ ]:
A+5

0     7
1     9
2    11
dtype: int64

In [ ]:
A.subtract(B, axis=0)


0    1
1    1
2    1
dtype: int64

In [ ]:
df1['A']-df1['C']

2021-02-25   -1.551355
2021-02-26   -1.792198
2021-02-27   -0.776359
2021-02-28   -0.698883
2021-03-01   -0.184756
2021-03-02    1.748717
2021-03-03    0.585210
2021-03-04    0.069477
2021-03-05   -0.450624
2021-03-06    0.943732
Freq: D, dtype: float64

In [ ]:
df1.subtract(df1['C'], axis=0)

A         B    C         D
2021-02-25 -1.551355 -1.155650  0.0 -1.724387
2021-02-26 -1.792198 -2.432273  0.0  0.696906
2021-02-27 -0.776359  0.225959  0.0  2.098976
2021-02-28 -0.698883  0.548057  0.0 -0.171094
2021-03-01 -0.184756  0.191573  0.0  1.177291
2021-03-02  1.748717 -0.579091  0.0  0.238532
2021-03-03  0.585210 -0.365056  0.0  0.053356
2021-03-04  0.069477  0.503607  0.0  1.528294
2021-03-05 -0.450624  0.012885  0.0  0.111368
2021-03-06  0.943732  1.117869  0.0 -0.608026

* Ranking and Sorting

In [ ]:
df3 = pd.DataFrame({'A' : [1,2,3,4,5],
                   'B' : pd.date_range('20200225' , periods=5),
                   'C' : pd.Series([5,10,9,65,4]),
                   'D' : pd.Series(5, index=(np.arange(5))),
                   'E' : pd.Categorical(["Train","Train","Test","Train","Test"]),
                   'F' : 'Workshop'})

In [ ]:
df3

A          B   C  D      E         F
0  1 2020-02-25   5  5  Train  Workshop
1  2 2020-02-26  10  5  Train  Workshop
2  3 2020-02-27   9  5   Test  Workshop
3  4 2020-02-28  65  5  Train  Workshop
4  5 2020-02-29   4  5   Test  Workshop

In [ ]:
df3['Ranking'] = df3['C'].rank(ascending = 1)
df3.sort_values(by='C')

A          B   C  D      E         F  Ranking
4  5 2020-02-29   4  5   Test  Workshop      1.0
0  1 2020-02-25   5  5  Train  Workshop      2.0
2  3 2020-02-27   9  5   Test  Workshop      3.0
1  2 2020-02-26  10  5  Train  Workshop      4.0
3  4 2020-02-28  65  5  Train  Workshop      5.0

In [ ]:
del df3['Ranking']
df3.reset_index(drop=True, inplace=True)

In [ ]:
df3 = df3.set_index('Ranking')

In [ ]:
df3

A          B   C  D      E         F
Ranking                                      
2.0      1 2020-02-25   5  5  Train  Workshop
4.0      2 2020-02-26  10  5  Train  Workshop
3.0      3 2020-02-27   9  5   Test  Workshop
5.0      4 2020-02-28  65  5  Train  Workshop
1.0      5 2020-02-29   4  5   Test  Workshop

In [ ]:
df3.sort_index()

A          B   C  D      E         F
Ranking                                      
1.0      5 2020-02-29   4  5   Test  Workshop
2.0      1 2020-02-25   5  5  Train  Workshop
3.0      3 2020-02-27   9  5   Test  Workshop
4.0      2 2020-02-26  10  5  Train  Workshop
5.0      4 2020-02-28  65  5  Train  Workshop

*  Duplicate Labels
* By default, for each set of duplicated values, the first occurrence is set to False and all others to True:

In [ ]:
book_list = pd.Series(['The Lord of the Rings','The Kite Runner','Harry Potter','Slaughterhouse-Five'], index=['J.R.R. Tolkien','Khaled Hosseini','Khaled Hosseini','Kurt Vonnegut'])

In [ ]:
book_list

J.R.R. Tolkien     The Lord of the Rings
Khaled Hosseini          The Kite Runner
Khaled Hosseini             Harry Potter
Kurt Vonnegut        Slaughterhouse-Five
dtype: object

In [ ]:
book_list.index.name="Authors"

In [ ]:
book_list

Authors
J.R.R. Tolkien     The Lord of the Rings
Khaled Hosseini          The Kite Runner
Khaled Hosseini             Harry Potter
Kurt Vonnegut        Slaughterhouse-Five
dtype: object

In [ ]:
book_list.index.duplicated()

array([False, False,  True, False])

In [ ]:
book_list.index.is_unique

False

* Correlation and Covariance

Compute pairwise covariance of columns, excluding NA/null values.
Compute the pairwise covariance among the series of a DataFrame. The returned data frame is the covariance matrix of the columns of the DataFrame.

In [ ]:
df4 = pd.DataFrame(np.random.randn(4,4),columns=['A','B','C','D'])

In [ ]:
df4

A         B         C         D
0  0.773492  1.412294  1.119953 -0.867824
1 -1.250708  0.544314  1.342767  0.450805
2 -1.082732 -0.118267 -1.192071 -0.110244
3 -0.652083 -0.088253  1.775704  1.870931

In [ ]:
df1.cov()

A         B         C         D
A  0.241097 -0.114788 -0.131036 -0.266792
B -0.114788  0.642624  0.156433  0.148332
C -0.131036  0.156433  0.696723  0.522541
D -0.266792  0.148332  0.522541  1.559569

The output dataframe can be interpreted as for any cell, row variable correlation with the column variable is the value of the cell. As mentioned earlier, that the correlation of a variable with itself is 1. For that reason all the diagonal values are 1.00

In [ ]:
df1.corr()

A         B         C         D
A  1.000000 -0.291622 -0.319716 -0.435085
B -0.291622  1.000000  0.233787  0.148168
C -0.319716  0.233787  1.000000  0.501289
D -0.435085  0.148168  0.501289  1.000000